app:
  profile: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-9c9jf-kr.vpc-pub-cdb.ntruss.com:3306/aicfo?&zeroDateTimeBehavior=convertToNull&autoReconnect=true&noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: metassom
    password: metassom_2022
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 26000
    initialization-mode: always
    initialize: true
    sql-script-encoding: utf-8
    continue-on-error: true

# server
server:
  tomcat:
    basedir: /home/labshigh/logs/nftmoa-internal-api

logging:
  file: /home/labshigh/logs/nftmoa-internal-api/common.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
    rolling-file-name: /home/labshigh/logs/nftmoa-internal-api/common.log.%d{yyyy-MM-dd}.%i.gz
  level:
    com:
      labshigh:
        aicfo: DEBUG

ncloud:
  access-key: 0EB353356DD94BC5AA69
  secret-key: AE5FB443EC6C50B3F856FD084EF4FE19EA6FF7A9
  mail-storage:
    end-point: https://mail.apigw.ntruss.com/api/v1/mails
    email-verify-template-id: 8260
    tokenExpirationTime: 1440 # 60*60*24
  sms-storage:
    end-point: https://sens.apigw.ntruss.com/sms/v2
    service-id: ncp:sms:kr:278692135831:pbcninc_com
    send-url: /services/${ncloud.sms-storage.service-id}/messages
    from-phone-number: "025582305"
    expirationTime: 1440 # 60*60*24
  ses:
    end-point: email-smtp.ap-southeast-1.amazonaws.com
    port: 2587
    access-key: AKIA2VA4NRAZE7SZNKOP
    secret-key: BMZzHdKLmlLhDWCgd9C0NT6rpoxb1V0mGeEGYwLsqZuy
    sender: info@aicfo.vip
aws:
  access-key: AKIA2VA4NRAZCXV6ZD6C
  secret-key: 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
  object-storage:
    end-point: aicfo-bucket.s3.ap-southeast-1.amazonaws.com
    region: ap-southeast-1
    bucket: aicfo-bucket

telegram:
  access_token: 6253167396:AAH8iFREQ9QcJkRTZCZPxHL-FbaadILqacI
  chat_id: -1001590574818
  main_wallet_withdrawal_chat_id: -1001760450726
  admin_tracking_chat_id: -1001581943398
