app:
  profile: local

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## 운영
    url: ENC(fT6mG6NJRqriL5+9qp/fGUExe+gniMhcjcC667TzWhGdaMSajomv/zonz98Lt25t8t/9DHKhbLbLUdzGKTDC6Ase/uz68xU8vkGI8a4QTbO29qIP8VOFWk1dMvyb/WoEFprrMrdtiJ73T6wc5XzY3K0LJBgQxFRmeWJekPhWhsc7NSkQUTDCzGPs6RqdnKK4M7umynxmEDTtsi9lehd+U7lo89VdOUhelDnhKoaEnFzUkSDJTW9fgVZ9BoCAcGPgRj5D04j9dviCyfRA6/k438zQDH3uU39DG8dtF2UEbi66HzLBJhJ0hA==)
    username: ENC(R/AJTVoIauIU45Qex9CIjQ==)
    password: ENC(gzJfFMAGivHTOY3iRNHth+D0EnzHS+s7ed5fxHNLYWc=)

    ## 로컬
    #url: ENC(imjnim2xA7GBWJs751hz8Uf0XAaomM/3hvbuYmjuoxtmdkGrC3JO0+z48y0G7EF1O8X8m6tNxkEI5A6gy/sjPeHrMe/ELyWP0V5n1wZmk5thSNPjp0nH0b+J58WluvZyO3OXmmdaJyi+T1j07l5jnLXT0UHg6Sl1hV++OZDRkyrmE9y6hPBmAs8BjABGWJ/suUBEItCwY8tPPfAT35BGWpe9P6P9nOl+UpqcueOjamy1tMIgosz1hn0EUN/gMTNk/9/Ra7+UVUlY/8u203HrMA==)
    #username: ENC(aNb6Upei9ctFn+hApf6vAw==)
    #password: ENC(MO00GPzcxsSVdhfH3B5hm8qDukUAnm0U)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 26000
    initialization-mode: always
    initialize: true
    sql-script-encoding: utf-8
    continue-on-error: true

# server
server:
  tomcat:
    basedir: /tmp/labshigh/logs/aicfo-internal-api

logging:
  file: /tmp/labshigh/logs/aicfo-internal-api/common.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
    rolling-file-name: /tmp/labshigh/logs/aicfo-internal-api/common.log.%d{yyyy-MM-dd}.%i.gz
  level:
    com:
      labshigh:
        aicfo: DEBUG

ncloud:
  access-key: 0EB353356DD94BC5AA69
  secret-key: AE5FB443EC6C50B3F856FD084EF4FE19EA6FF7A9
  object-storage:
    end-point: kr.object.ncloudstorage.com
    region: kr-standard
    bucket: aicfo-s3
  mail-storage:
    end-point: https://mail.apigw.ntruss.com/api/v1/mails
    email-verify-template-id: 8260
    tokenExpirationTime: 1440 # 60*60*24
    access-key: AKIA2VA4NRAZE7SZNKOP
    secret-key: BMZzHdKLmlLhDWCgd9C0NT6rpoxb1V0mGeEGYwLsqZuy
    sender: info@aicfo.vip
    port: 2587
  sms-storage:
    end-point: https://sens.apigw.ntruss.com/sms/v2
    service-id: ncp:sms:kr:278692135831:pbcninc_com
    send-url: /services/${ncloud.sms-storage.service-id}/messages
    from-phone-number: "01096361079"
    expirationTime: 1440 # 60*60*24


aws:
  access-key: AKIA2VA4NRAZCXV6ZD6C
  secret-key: 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
  object-storage:
    end-point: aicfo-bucket.s3.ap-southeast-1.amazonaws.com
    region: ap-southeast-1
    bucket: aicfo-bucket
  ses:
    end-point: email-smtp.ap-southeast-1.amazonaws.com
    port: 2587
    access-key: AKIA2VA4NRAZE7SZNKOP
    secret-key: BMZzHdKLmlLhDWCgd9C0NT6rpoxb1V0mGeEGYwLsqZuy
    sender: info@aicfo.vip
aicfo:
  wallet:
    api: http://13.213.112.24:9000

telegram:
  access_token: 6253167396:AAH8iFREQ9QcJkRTZCZPxHL-FbaadILqacI
  chat_id: -1001590574818
  main_wallet_withdrawal_chat_id: -1001760450726
  admin_tracking_chat_id: -1001581943398

    #Jasypt
    #jasypt:
    #props:
  #file-path: /Users/home/jasypt.props